{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "headscale.fullname" . }}
  labels: {{- include "headscale.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
{{- end }}
