{{- if and .Values.postgresql.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "headscale.postgresql.fullname" . }}
  labels: {{- include "headscale.postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "headscale.postgresql.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "headscale.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: control-plane
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: backup
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - { port: 5432, protocol: TCP }
  egress:
    - to:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: kube-system }
      ports:
        - { port: 53, protocol: UDP }
        - { port: 53, protocol: TCP }
{{- end }}
