{{- if and .Values.postgresql.enabled (not .Values.vault.enabled) (not .Values.postgresql.external.enabled) (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgresql-auth" (include "headscale.fullname" .) }}
  labels: {{- include "headscale.postgresql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
