apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}
  labels: {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - { name: http,    port: 8080,  targetPort: http }
    - { name: metrics, port: 9090,  targetPort: metrics }
    - { name: grpc,    port: 50443, targetPort: grpc }
{{- if .Values.derp.embedded }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}-stun
  labels: {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - { name: stun, port: {{ .Values.derp.stunPort }}, targetPort: stun, protocol: UDP }
{{- end }}
{{- if eq .Values.database.type "sqlite" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}-headless
  labels: {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - { name: http, port: 8080, targetPort: http }
{{- end }}
