{{- if and .Values.ui.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  podSelector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-ui
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        {{- include "headscale.netpol.ingressControllerFrom" . | nindent 8 }}
      ports: [ { port: 8080, protocol: TCP } ]
  egress:
    - to:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: kube-system }
      ports:
        - { port: 53, protocol: UDP }
        - { port: 53, protocol: TCP }
{{- end }}
