{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "headscale.fullname" . }}-vault-db
  labels: {{- include "headscale.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.authRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  type: kv-v2
  path: {{ .Values.vault.path | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | default "1h" | quote }}
  destination:
    name: {{ .Values.vault.destinationSecretName | default (printf "%s-vault-db" (include "headscale.fullname" .)) }}
    create: true
    labels: {{- include "headscale.labels" . | nindent 6 }}
  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ include "headscale.postgresql.fullname" . }}
    - kind: {{ if eq .Values.database.type "sqlite" }}StatefulSet{{ else }}Deployment{{ end }}
      name: {{ include "headscale.fullname" . }}
{{- end }}
